application: vp-licensing
version: v1

runtime: go
api_version: go1

handlers:

- url: /
  login: admin
  static_files: static/index.html
  upload: static/index.html

- url: /static
  static_dir: static

- url: /.*
  login: admin
  script: _go_app
